name: Build and upload WebGL artifact onto a target branch

on:
  push:
    branches: [ main ]
env:
  UNITY_LICENSE : ${{secrets.UNITY_LICENSE_2019}} # This needs to be setup in the github repository settings
  UNITY_VERSION : 2022.2.21f1
  PROJECT_PATH  : PopTartArena/
  BUILD_NAME    : WebBuild
  TARGET_BRANCH : builds

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name : Make a webGL build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout main branch
        uses : actions/checkout@v2
        
    #  Store library in cache
      - uses: actions/cache@v2
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: CachedLibrary

      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-14
        with:
          allowDirtyBuild: true # TODO - investigate
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: WebGL
          buildsPath: .
          buildName: ${{ env.BUILD_NAME }}
        #  customImage: 'amoghsubhedar/unity-webgl-editor:latest' 
		# using a custom docker image because the default ones for this unity version don't have ffmpeg

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}
          path: WebGL/
      
  commit_build:
    name : Push build on the builds branch
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout builds branch
        uses : actions/checkout@v2
        with :
          ref: ${{ env.TARGET_BRANCH }}
      
      - name: Download artifact from previous job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}
      
      # This is only needed if the target branch does not already have the ${{ env.BUILD_NAME }} directory
      - name: Show git status
        run : git add . && git status

      - name: Deploy WebGL build on github pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy web build
          file_pattern: ${{ env.BUILD_NAME }}/Build/* ${{ env.BUILD_NAME }}/TemplateData/*
           # Optional: Skip internal call to `git fetch`
          skip_fetch: true
